# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/dane/projects/autodane/autodane/main/mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1192, 592)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lblSummaryLabel = QtWidgets.QLabel(self.tab)
        self.lblSummaryLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lblSummaryLabel.setObjectName(_fromUtf8("lblSummaryLabel"))
        self.verticalLayout_4.addWidget(self.lblSummaryLabel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tblOpenPortsSummary = QtWidgets.QTableWidget(self.groupBox_5)
        self.tblOpenPortsSummary.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblOpenPortsSummary.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblOpenPortsSummary.setObjectName(_fromUtf8("tblOpenPortsSummary"))
        self.tblOpenPortsSummary.setColumnCount(2)
        self.tblOpenPortsSummary.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblOpenPortsSummary.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblOpenPortsSummary.setHorizontalHeaderItem(1, item)
        self.gridLayout_5.addWidget(self.tblOpenPortsSummary, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.tblDomains = QtWidgets.QTableWidget(self.groupBox_7)
        self.tblDomains.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblDomains.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblDomains.setObjectName(_fromUtf8("tblDomains"))
        self.tblDomains.setColumnCount(3)
        self.tblDomains.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblDomains.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDomains.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDomains.setHorizontalHeaderItem(2, item)
        self.gridLayout_6.addWidget(self.tblDomains, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_7)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.tblVulnsSummary = QtWidgets.QTableWidget(self.groupBox_6)
        self.tblVulnsSummary.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblVulnsSummary.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblVulnsSummary.setObjectName(_fromUtf8("tblVulnsSummary"))
        self.tblVulnsSummary.setColumnCount(2)
        self.tblVulnsSummary.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblVulnsSummary.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblVulnsSummary.setHorizontalHeaderItem(1, item)
        self.gridLayout_7.addWidget(self.tblVulnsSummary, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_6)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.tblCredsSummary = QtWidgets.QTableWidget(self.groupBox_8)
        self.tblCredsSummary.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblCredsSummary.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblCredsSummary.setObjectName(_fromUtf8("tblCredsSummary"))
        self.tblCredsSummary.setColumnCount(2)
        self.tblCredsSummary.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblCredsSummary.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblCredsSummary.setHorizontalHeaderItem(1, item)
        self.gridLayout_8.addWidget(self.tblCredsSummary, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_8)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_9.setMaximumSize(QtCore.QSize(16777215, 50))
        self.groupBox_9.setTitle(_fromUtf8(""))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_3.setContentsMargins(0,0,0,0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.btnUpdateSummary = QtWidgets.QPushButton(self.groupBox_9)
        self.btnUpdateSummary.setObjectName(_fromUtf8("btnUpdateSummary"))
        self.horizontalLayout_4.addWidget(self.btnUpdateSummary)
        self.cbxUpdateSummary = QtWidgets.QCheckBox(self.groupBox_9)
        self.cbxUpdateSummary.setObjectName(_fromUtf8("cbxUpdateSummary"))
        self.horizontalLayout_4.addWidget(self.cbxUpdateSummary)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_9)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frame_4 = QtWidgets.QFrame(self.tab_2)
        self.frame_4.setMinimumSize(QtCore.QSize(350, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.cbxHostsFilterVisible = QtWidgets.QCheckBox(self.frame_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cbxHostsFilterVisible.setFont(font)
        self.cbxHostsFilterVisible.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cbxHostsFilterVisible.setChecked(True)
        self.cbxHostsFilterVisible.setObjectName(_fromUtf8("cbxHostsFilterVisible"))
        self.horizontalLayout_24.addWidget(self.cbxHostsFilterVisible)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem1)
        self.verticalLayout_18.addLayout(self.horizontalLayout_24)
        self.frameHostsFilter = QtWidgets.QFrame(self.frame_4)
        self.frameHostsFilter.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameHostsFilter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameHostsFilter.setObjectName(_fromUtf8("frameHostsFilter"))
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frameHostsFilter)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.cmbHostFilterField = QtWidgets.QComboBox(self.frameHostsFilter)
        self.cmbHostFilterField.setMinimumSize(QtCore.QSize(150, 0))
        self.cmbHostFilterField.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cmbHostFilterField.setObjectName(_fromUtf8("cmbHostFilterField"))
        self.cmbHostFilterField.addItem(_fromUtf8(""))
        self.cmbHostFilterField.setItemText(0, _fromUtf8(""))
        self.cmbHostFilterField.addItem(_fromUtf8(""))
        self.cmbHostFilterField.addItem(_fromUtf8(""))
        self.cmbHostFilterField.addItem(_fromUtf8(""))
        self.cmbHostFilterField.addItem(_fromUtf8(""))
        self.horizontalLayout_31.addWidget(self.cmbHostFilterField)
        self.txtHostFilterValue = QtWidgets.QLineEdit(self.frameHostsFilter)
        self.txtHostFilterValue.setObjectName(_fromUtf8("txtHostFilterValue"))
        self.horizontalLayout_31.addWidget(self.txtHostFilterValue)
        self.verticalLayout_17.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem2)
        self.btnSearchHosts = QtWidgets.QPushButton(self.frameHostsFilter)
        self.btnSearchHosts.setObjectName(_fromUtf8("btnSearchHosts"))
        self.horizontalLayout_33.addWidget(self.btnSearchHosts)
        self.verticalLayout_17.addLayout(self.horizontalLayout_33)
        self.verticalLayout_18.addWidget(self.frameHostsFilter)
        self.tvHosts = QtWidgets.QTreeView(self.frame_4)
        self.tvHosts.setMinimumSize(QtCore.QSize(0, 0))
        self.tvHosts.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tvHosts.setObjectName(_fromUtf8("tvHosts"))
        self.verticalLayout_18.addWidget(self.tvHosts)
        self.gridLayout_2.addWidget(self.frame_4, 0, 0, 1, 1)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setMinimumSize(QtCore.QSize(110, 0))
        self.label_2.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.lblComputerName = QtWidgets.QLabel(self.tab_3)
        self.lblComputerName.setText(_fromUtf8(""))
        self.lblComputerName.setObjectName(_fromUtf8("lblComputerName"))
        self.horizontalLayout_5.addWidget(self.lblComputerName)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setMinimumSize(QtCore.QSize(110, 0))
        self.label_4.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.lblOS = QtWidgets.QLabel(self.tab_3)
        self.lblOS.setText(_fromUtf8(""))
        self.lblOS.setObjectName(_fromUtf8("lblOS"))
        self.horizontalLayout_6.addWidget(self.lblOS)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setMinimumSize(QtCore.QSize(110, 0))
        self.label_6.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_7.addWidget(self.label_6)
        self.lblArchitecture = QtWidgets.QLabel(self.tab_3)
        self.lblArchitecture.setText(_fromUtf8(""))
        self.lblArchitecture.setObjectName(_fromUtf8("lblArchitecture"))
        self.horizontalLayout_7.addWidget(self.lblArchitecture)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setMinimumSize(QtCore.QSize(110, 0))
        self.label_8.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_8.addWidget(self.label_8)
        self.lblLanguage = QtWidgets.QLabel(self.tab_3)
        self.lblLanguage.setText(_fromUtf8(""))
        self.lblLanguage.setObjectName(_fromUtf8("lblLanguage"))
        self.horizontalLayout_8.addWidget(self.lblLanguage)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setMinimumSize(QtCore.QSize(110, 0))
        self.label_10.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_9.addWidget(self.label_10)
        self.lblDomain = QtWidgets.QLabel(self.tab_3)
        self.lblDomain.setText(_fromUtf8(""))
        self.lblDomain.setObjectName(_fromUtf8("lblDomain"))
        self.horizontalLayout_9.addWidget(self.lblDomain)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.tblHostPorts = QtWidgets.QTableWidget(self.groupBox_13)
        self.tblHostPorts.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblHostPorts.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblHostPorts.setObjectName(_fromUtf8("tblHostPorts"))
        self.tblHostPorts.setColumnCount(1)
        self.tblHostPorts.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblHostPorts.setHorizontalHeaderItem(0, item)
        self.gridLayout_9.addWidget(self.tblHostPorts, 0, 0, 1, 1)
        self.horizontalLayout_10.addWidget(self.groupBox_13)
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.tblHostVulns = QtWidgets.QTableWidget(self.groupBox_14)
        self.tblHostVulns.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblHostVulns.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblHostVulns.setObjectName(_fromUtf8("tblHostVulns"))
        self.tblHostVulns.setColumnCount(2)
        self.tblHostVulns.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblHostVulns.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblHostVulns.setHorizontalHeaderItem(1, item)
        self.gridLayout_11.addWidget(self.tblHostVulns, 0, 0, 1, 1)
        self.horizontalLayout_10.addWidget(self.groupBox_14)
        self.groupBox_15 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_15)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.tblHostCredsSummary = QtWidgets.QTableWidget(self.groupBox_15)
        self.tblHostCredsSummary.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblHostCredsSummary.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblHostCredsSummary.setObjectName(_fromUtf8("tblHostCredsSummary"))
        self.tblHostCredsSummary.setColumnCount(2)
        self.tblHostCredsSummary.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblHostCredsSummary.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblHostCredsSummary.setHorizontalHeaderItem(1, item)
        self.gridLayout_10.addWidget(self.tblHostCredsSummary, 0, 0, 1, 1)
        self.horizontalLayout_10.addWidget(self.groupBox_15)
        self.verticalLayout_10.addLayout(self.horizontalLayout_10)
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_6)
        self.tabWidget_4.setObjectName(_fromUtf8("tabWidget_4"))
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.tblLocalCreds = QtWidgets.QTableWidget(self.tab_4)
        self.tblLocalCreds.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblLocalCreds.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblLocalCreds.setObjectName(_fromUtf8("tblLocalCreds"))
        self.tblLocalCreds.setColumnCount(4)
        self.tblLocalCreds.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblLocalCreds.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblLocalCreds.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblLocalCreds.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblLocalCreds.setHorizontalHeaderItem(3, item)
        self.gridLayout_15.addWidget(self.tblLocalCreds, 0, 0, 1, 1)
        self.tabWidget_4.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.tblDomainCreds = QtWidgets.QTableWidget(self.tab_5)
        self.tblDomainCreds.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblDomainCreds.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblDomainCreds.setObjectName(_fromUtf8("tblDomainCreds"))
        self.tblDomainCreds.setColumnCount(3)
        self.tblDomainCreds.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblDomainCreds.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDomainCreds.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDomainCreds.setHorizontalHeaderItem(2, item)
        self.gridLayout_16.addWidget(self.tblDomainCreds, 0, 0, 1, 1)
        self.tabWidget_4.addTab(self.tab_5, _fromUtf8(""))
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName(_fromUtf8("tab_17"))
        self.gridLayout_17 = QtWidgets.QGridLayout(self.tab_17)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.tblAvailableTokens = QtWidgets.QTableWidget(self.tab_17)
        self.tblAvailableTokens.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblAvailableTokens.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblAvailableTokens.setObjectName(_fromUtf8("tblAvailableTokens"))
        self.tblAvailableTokens.setColumnCount(1)
        self.tblAvailableTokens.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblAvailableTokens.setHorizontalHeaderItem(0, item)
        self.gridLayout_17.addWidget(self.tblAvailableTokens, 0, 0, 1, 1)
        self.tabWidget_4.addTab(self.tab_17, _fromUtf8(""))
        self.gridLayout_12.addWidget(self.tabWidget_4, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_7)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.tblExploitLogs = QtWidgets.QTableWidget(self.tab_7)
        self.tblExploitLogs.setMinimumSize(QtCore.QSize(0, 0))
        self.tblExploitLogs.setMaximumSize(QtCore.QSize(16777215, 150))
        self.tblExploitLogs.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblExploitLogs.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblExploitLogs.setObjectName(_fromUtf8("tblExploitLogs"))
        self.tblExploitLogs.setColumnCount(1)
        self.tblExploitLogs.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblExploitLogs.setHorizontalHeaderItem(0, item)
        self.verticalLayout_8.addWidget(self.tblExploitLogs)
        self.txtExploitLog = QtWidgets.QTextEdit(self.tab_7)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setItalic(False)
        self.txtExploitLog.setFont(font)
        self.txtExploitLog.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.txtExploitLog.setObjectName(_fromUtf8("txtExploitLog"))
        self.verticalLayout_8.addWidget(self.txtExploitLog)
        self.tabWidget_2.addTab(self.tab_7, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget_2, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.btnOpenRDPSession = QtWidgets.QPushButton(self.tab_2)
        self.btnOpenRDPSession.setObjectName(_fromUtf8("btnOpenRDPSession"))
        self.horizontalLayout.addWidget(self.btnOpenRDPSession)
        self.btnAddHost = QtWidgets.QPushButton(self.tab_2)
        self.btnAddHost.setObjectName(_fromUtf8("btnAddHost"))
        self.horizontalLayout.addWidget(self.btnAddHost)
        self.btnUpdateHosts = QtWidgets.QPushButton(self.tab_2)
        self.btnUpdateHosts.setMaximumSize(QtCore.QSize(0, 16777215))
        self.btnUpdateHosts.setObjectName(_fromUtf8("btnUpdateHosts"))
        self.horizontalLayout.addWidget(self.btnUpdateHosts)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_25 = QtWidgets.QWidget()
        self.tab_25.setObjectName(_fromUtf8("tab_25"))
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.tab_25)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_7 = QtWidgets.QLabel(self.tab_25)
        self.label_7.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_26.addWidget(self.label_7)
        self.cmbVulnerabilities = QtWidgets.QComboBox(self.tab_25)
        self.cmbVulnerabilities.setObjectName(_fromUtf8("cmbVulnerabilities"))
        self.horizontalLayout_26.addWidget(self.cmbVulnerabilities)
        self.verticalLayout_16.addLayout(self.horizontalLayout_26)
        self.tblVulnerableHosts = QtWidgets.QTableWidget(self.tab_25)
        self.tblVulnerableHosts.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tblVulnerableHosts.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblVulnerableHosts.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblVulnerableHosts.setObjectName(_fromUtf8("tblVulnerableHosts"))
        self.tblVulnerableHosts.setColumnCount(5)
        self.tblVulnerableHosts.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblVulnerableHosts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblVulnerableHosts.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblVulnerableHosts.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblVulnerableHosts.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblVulnerableHosts.setHorizontalHeaderItem(4, item)
        self.verticalLayout_16.addWidget(self.tblVulnerableHosts)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem4)
        self.btnRefreshVulnerabilitiesTab = QtWidgets.QPushButton(self.tab_25)
        self.btnRefreshVulnerabilitiesTab.setObjectName(_fromUtf8("btnRefreshVulnerabilitiesTab"))
        self.horizontalLayout_30.addWidget(self.btnRefreshVulnerabilitiesTab)
        self.verticalLayout_16.addLayout(self.horizontalLayout_30)
        self.tabWidget.addTab(self.tab_25, _fromUtf8(""))
        self.tab_21 = QtWidgets.QWidget()
        self.tab_21.setObjectName(_fromUtf8("tab_21"))
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab_21)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.tblDomains_2 = QtWidgets.QTableWidget(self.tab_21)
        self.tblDomains_2.setMaximumSize(QtCore.QSize(350, 16777215))
        self.tblDomains_2.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblDomains_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblDomains_2.setObjectName(_fromUtf8("tblDomains_2"))
        self.tblDomains_2.setColumnCount(1)
        self.tblDomains_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblDomains_2.setHorizontalHeaderItem(0, item)
        self.horizontalLayout_13.addWidget(self.tblDomains_2)
        self.tabWidget_6 = QtWidgets.QTabWidget(self.tab_21)
        self.tabWidget_6.setObjectName(_fromUtf8("tabWidget_6"))
        self.tab_22 = QtWidgets.QWidget()
        self.tab_22.setObjectName(_fromUtf8("tab_22"))
        self.gridLayout_35 = QtWidgets.QGridLayout(self.tab_22)
        self.gridLayout_35.setObjectName(_fromUtf8("gridLayout_35"))
        self.tblDomainControllers = QtWidgets.QTableWidget(self.tab_22)
        self.tblDomainControllers.setObjectName(_fromUtf8("tblDomainControllers"))
        self.tblDomainControllers.setColumnCount(2)
        self.tblDomainControllers.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblDomainControllers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDomainControllers.setHorizontalHeaderItem(1, item)
        self.gridLayout_35.addWidget(self.tblDomainControllers, 0, 0, 1, 1)
        self.tabWidget_6.addTab(self.tab_22, _fromUtf8(""))
        self.tab_24 = QtWidgets.QWidget()
        self.tab_24.setObjectName(_fromUtf8("tab_24"))
        self.gridLayout_36 = QtWidgets.QGridLayout(self.tab_24)
        self.gridLayout_36.setObjectName(_fromUtf8("gridLayout_36"))
        self.tblDomainControllerCredMap = QtWidgets.QTableWidget(self.tab_24)
        self.tblDomainControllerCredMap.setObjectName(_fromUtf8("tblDomainControllerCredMap"))
        self.tblDomainControllerCredMap.setColumnCount(5)
        self.tblDomainControllerCredMap.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblDomainControllerCredMap.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDomainControllerCredMap.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDomainControllerCredMap.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDomainControllerCredMap.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblDomainControllerCredMap.setHorizontalHeaderItem(4, item)
        self.gridLayout_36.addWidget(self.tblDomainControllerCredMap, 0, 0, 1, 1)
        self.tabWidget_6.addTab(self.tab_24, _fromUtf8(""))
        self.tab_23 = QtWidgets.QWidget()
        self.tab_23.setObjectName(_fromUtf8("tab_23"))
        self.gridLayout_43 = QtWidgets.QGridLayout(self.tab_23)
        self.gridLayout_43.setObjectName(_fromUtf8("gridLayout_43"))
        self.groupBox_21 = QtWidgets.QGroupBox(self.tab_23)
        self.groupBox_21.setObjectName(_fromUtf8("groupBox_21"))
        self.gridLayout_37 = QtWidgets.QGridLayout(self.groupBox_21)
        self.gridLayout_37.setObjectName(_fromUtf8("gridLayout_37"))
        self.tblDomainGroups = QtWidgets.QTableWidget(self.groupBox_21)
        self.tblDomainGroups.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblDomainGroups.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblDomainGroups.setObjectName(_fromUtf8("tblDomainGroups"))
        self.tblDomainGroups.setColumnCount(1)
        self.tblDomainGroups.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblDomainGroups.setHorizontalHeaderItem(0, item)
        self.gridLayout_37.addWidget(self.tblDomainGroups, 0, 0, 1, 1)
        self.gridLayout_43.addWidget(self.groupBox_21, 0, 0, 2, 1)
        self.groupBox_22 = QtWidgets.QGroupBox(self.tab_23)
        self.groupBox_22.setObjectName(_fromUtf8("groupBox_22"))
        self.gridLayout_38 = QtWidgets.QGridLayout(self.groupBox_22)
        self.gridLayout_38.setObjectName(_fromUtf8("gridLayout_38"))
        self.tblDomainGroupUsers = QtWidgets.QTableWidget(self.groupBox_22)
        self.tblDomainGroupUsers.setObjectName(_fromUtf8("tblDomainGroupUsers"))
        self.tblDomainGroupUsers.setColumnCount(1)
        self.tblDomainGroupUsers.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblDomainGroupUsers.setHorizontalHeaderItem(0, item)
        self.gridLayout_38.addWidget(self.tblDomainGroupUsers, 0, 0, 1, 1)
        self.gridLayout_43.addWidget(self.groupBox_22, 0, 1, 1, 1)
        self.groupBox_23 = QtWidgets.QGroupBox(self.tab_23)
        self.groupBox_23.setObjectName(_fromUtf8("groupBox_23"))
        self.gridLayout_39 = QtWidgets.QGridLayout(self.groupBox_23)
        self.gridLayout_39.setObjectName(_fromUtf8("gridLayout_39"))
        self.tblDomainSubGroups = QtWidgets.QTableWidget(self.groupBox_23)
        self.tblDomainSubGroups.setObjectName(_fromUtf8("tblDomainSubGroups"))
        self.tblDomainSubGroups.setColumnCount(1)
        self.tblDomainSubGroups.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblDomainSubGroups.setHorizontalHeaderItem(0, item)
        self.gridLayout_39.addWidget(self.tblDomainSubGroups, 0, 0, 1, 1)
        self.gridLayout_43.addWidget(self.groupBox_23, 1, 1, 1, 1)
        self.tabWidget_6.addTab(self.tab_23, _fromUtf8(""))
        self.horizontalLayout_13.addWidget(self.tabWidget_6)
        self.verticalLayout_13.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem5)
        self.btnUpdateDomains = QtWidgets.QPushButton(self.tab_21)
        self.btnUpdateDomains.setObjectName(_fromUtf8("btnUpdateDomains"))
        self.horizontalLayout_23.addWidget(self.btnUpdateDomains)
        self.verticalLayout_13.addLayout(self.horizontalLayout_23)
        self.tabWidget.addTab(self.tab_21, _fromUtf8(""))
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_8)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(450, 16777215))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_25 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.tblWebsites = QtWidgets.QTableWidget(self.groupBox)
        self.tblWebsites.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblWebsites.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblWebsites.setObjectName(_fromUtf8("tblWebsites"))
        self.tblWebsites.setColumnCount(5)
        self.tblWebsites.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblWebsites.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblWebsites.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblWebsites.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblWebsites.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblWebsites.setHorizontalHeaderItem(4, item)
        self.tblWebsites.verticalHeader().setSortIndicatorShown(False)
        self.gridLayout_25.addWidget(self.tblWebsites, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.gridLayout_27 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_27.setObjectName(_fromUtf8("gridLayout_27"))
        self.tabWidget_5 = QtWidgets.QTabWidget(self.groupBox_10)
        self.tabWidget_5.setObjectName(_fromUtf8("tabWidget_5"))
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName(_fromUtf8("tab_14"))
        self.gridLayout_29 = QtWidgets.QGridLayout(self.tab_14)
        self.gridLayout_29.setObjectName(_fromUtf8("gridLayout_29"))
        self.scrollArea = QtWidgets.QScrollArea(self.tab_14)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 98, 35))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_28 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_28.setObjectName(_fromUtf8("gridLayout_28"))
        self.lblWebsitesScreenshot = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblWebsitesScreenshot.setText(_fromUtf8(""))
        self.lblWebsitesScreenshot.setObjectName(_fromUtf8("lblWebsitesScreenshot"))
        self.gridLayout_28.addWidget(self.lblWebsitesScreenshot, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_29.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget_5.addTab(self.tab_14, _fromUtf8(""))
        self.tab_19 = QtWidgets.QWidget()
        self.tab_19.setObjectName(_fromUtf8("tab_19"))
        self.gridLayout_30 = QtWidgets.QGridLayout(self.tab_19)
        self.gridLayout_30.setObjectName(_fromUtf8("gridLayout_30"))
        self.txtWebsiteHtml = QtWidgets.QTextEdit(self.tab_19)
        self.txtWebsiteHtml.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.txtWebsiteHtml.setObjectName(_fromUtf8("txtWebsiteHtml"))
        self.gridLayout_30.addWidget(self.txtWebsiteHtml, 0, 0, 1, 1)
        self.tabWidget_5.addTab(self.tab_19, _fromUtf8(""))
        self.gridLayout_27.addWidget(self.tabWidget_5, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_10)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem6)
        self.btnUpdateWebsites = QtWidgets.QPushButton(self.tab_8)
        self.btnUpdateWebsites.setObjectName(_fromUtf8("btnUpdateWebsites"))
        self.horizontalLayout_16.addWidget(self.btnUpdateWebsites)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.tabWidget.addTab(self.tab_8, _fromUtf8(""))
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_9)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_9)
        self.tabWidget_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName(_fromUtf8("tab_10"))
        self.gridLayout_21 = QtWidgets.QGridLayout(self.tab_10)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.tblAllDomainCreds = QtWidgets.QTableWidget(self.tab_10)
        self.tblAllDomainCreds.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblAllDomainCreds.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblAllDomainCreds.setObjectName(_fromUtf8("tblAllDomainCreds"))
        self.tblAllDomainCreds.setColumnCount(5)
        self.tblAllDomainCreds.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblAllDomainCreds.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAllDomainCreds.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAllDomainCreds.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAllDomainCreds.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAllDomainCreds.setHorizontalHeaderItem(4, item)
        self.gridLayout_21.addWidget(self.tblAllDomainCreds, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_10, _fromUtf8(""))
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName(_fromUtf8("tab_13"))
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.tab_13)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.groupBox_18 = QtWidgets.QGroupBox(self.tab_13)
        self.groupBox_18.setObjectName(_fromUtf8("groupBox_18"))
        self.gridLayout_22 = QtWidgets.QGridLayout(self.groupBox_18)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.tblValidDomainCreds = QtWidgets.QTableWidget(self.groupBox_18)
        self.tblValidDomainCreds.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblValidDomainCreds.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblValidDomainCreds.setObjectName(_fromUtf8("tblValidDomainCreds"))
        self.tblValidDomainCreds.setColumnCount(4)
        self.tblValidDomainCreds.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblValidDomainCreds.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblValidDomainCreds.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblValidDomainCreds.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblValidDomainCreds.setHorizontalHeaderItem(3, item)
        self.gridLayout_22.addWidget(self.tblValidDomainCreds, 0, 0, 1, 1)
        self.horizontalLayout_15.addWidget(self.groupBox_18)
        self.groupBox_19 = QtWidgets.QGroupBox(self.tab_13)
        self.groupBox_19.setMaximumSize(QtCore.QSize(0, 16777215))
        self.groupBox_19.setObjectName(_fromUtf8("groupBox_19"))
        self.gridLayout_23 = QtWidgets.QGridLayout(self.groupBox_19)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.tblInvalidDomainCreds = QtWidgets.QTableWidget(self.groupBox_19)
        self.tblInvalidDomainCreds.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblInvalidDomainCreds.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblInvalidDomainCreds.setObjectName(_fromUtf8("tblInvalidDomainCreds"))
        self.tblInvalidDomainCreds.setColumnCount(4)
        self.tblInvalidDomainCreds.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblInvalidDomainCreds.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblInvalidDomainCreds.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblInvalidDomainCreds.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblInvalidDomainCreds.setHorizontalHeaderItem(3, item)
        self.gridLayout_23.addWidget(self.tblInvalidDomainCreds, 0, 0, 1, 1)
        self.horizontalLayout_15.addWidget(self.groupBox_19)
        self.tabWidget_3.addTab(self.tab_13, _fromUtf8(""))
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName(_fromUtf8("tab_11"))
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_11)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tblAllLocalCreds = QtWidgets.QTableWidget(self.tab_11)
        self.tblAllLocalCreds.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblAllLocalCreds.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblAllLocalCreds.setObjectName(_fromUtf8("tblAllLocalCreds"))
        self.tblAllLocalCreds.setColumnCount(4)
        self.tblAllLocalCreds.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblAllLocalCreds.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAllLocalCreds.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAllLocalCreds.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAllLocalCreds.setHorizontalHeaderItem(3, item)
        self.gridLayout_4.addWidget(self.tblAllLocalCreds, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_11, _fromUtf8(""))
        self.tab_18 = QtWidgets.QWidget()
        self.tab_18.setObjectName(_fromUtf8("tab_18"))
        self.gridLayout_24 = QtWidgets.QGridLayout(self.tab_18)
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.tblTokens = QtWidgets.QTableWidget(self.tab_18)
        self.tblTokens.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblTokens.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblTokens.setObjectName(_fromUtf8("tblTokens"))
        self.tblTokens.setColumnCount(1)
        self.tblTokens.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblTokens.setHorizontalHeaderItem(0, item)
        self.gridLayout_24.addWidget(self.tblTokens, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_18, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget_3)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.btnAddDomainCreds = QtWidgets.QPushButton(self.tab_9)
        self.btnAddDomainCreds.setObjectName(_fromUtf8("btnAddDomainCreds"))
        self.horizontalLayout_11.addWidget(self.btnAddDomainCreds)
        self.btnImportLoot = QtWidgets.QPushButton(self.tab_9)
        self.btnImportLoot.setObjectName(_fromUtf8("btnImportLoot"))
        self.horizontalLayout_11.addWidget(self.btnImportLoot)
        self.btnSyncJohnPotFile = QtWidgets.QPushButton(self.tab_9)
        self.btnSyncJohnPotFile.setObjectName(_fromUtf8("btnSyncJohnPotFile"))
        self.horizontalLayout_11.addWidget(self.btnSyncJohnPotFile)
        self.btnUpdateCreds = QtWidgets.QPushButton(self.tab_9)
        self.btnUpdateCreds.setObjectName(_fromUtf8("btnUpdateCreds"))
        self.horizontalLayout_11.addWidget(self.btnUpdateCreds)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.tabWidget.addTab(self.tab_9, _fromUtf8(""))
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName(_fromUtf8("tab_15"))
        self.gridLayout_34 = QtWidgets.QGridLayout(self.tab_15)
        self.gridLayout_34.setObjectName(_fromUtf8("gridLayout_34"))
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_15)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.tblTaskListPending = QtWidgets.QTableWidget(self.groupBox_4)
        self.tblTaskListPending.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblTaskListPending.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblTaskListPending.setObjectName(_fromUtf8("tblTaskListPending"))
        self.tblTaskListPending.setColumnCount(3)
        self.tblTaskListPending.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblTaskListPending.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTaskListPending.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTaskListPending.setHorizontalHeaderItem(2, item)
        self.gridLayout_18.addWidget(self.tblTaskListPending, 0, 0, 1, 1)
        self.verticalLayout_11.addWidget(self.groupBox_4)
        self.groupBox_20 = QtWidgets.QGroupBox(self.tab_15)
        self.groupBox_20.setObjectName(_fromUtf8("groupBox_20"))
        self.gridLayout_33 = QtWidgets.QGridLayout(self.groupBox_20)
        self.gridLayout_33.setObjectName(_fromUtf8("gridLayout_33"))
        self.tblTaskListPending_2 = QtWidgets.QTableWidget(self.groupBox_20)
        self.tblTaskListPending_2.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblTaskListPending_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblTaskListPending_2.setObjectName(_fromUtf8("tblTaskListPending_2"))
        self.tblTaskListPending_2.setColumnCount(3)
        self.tblTaskListPending_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblTaskListPending_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTaskListPending_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTaskListPending_2.setHorizontalHeaderItem(2, item)
        self.gridLayout_33.addWidget(self.tblTaskListPending_2, 0, 0, 1, 1)
        self.verticalLayout_11.addWidget(self.groupBox_20)
        self.gridLayout_34.addLayout(self.verticalLayout_11, 0, 0, 1, 1)
        self.groupBox_17 = QtWidgets.QGroupBox(self.tab_15)
        self.groupBox_17.setObjectName(_fromUtf8("groupBox_17"))
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox_17)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.tblTaskListInProgress = QtWidgets.QTableWidget(self.groupBox_17)
        self.tblTaskListInProgress.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblTaskListInProgress.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblTaskListInProgress.setObjectName(_fromUtf8("tblTaskListInProgress"))
        self.tblTaskListInProgress.setColumnCount(3)
        self.tblTaskListInProgress.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblTaskListInProgress.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTaskListInProgress.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTaskListInProgress.setHorizontalHeaderItem(2, item)
        self.gridLayout_20.addWidget(self.tblTaskListInProgress, 0, 0, 1, 1)
        self.gridLayout_34.addWidget(self.groupBox_17, 0, 1, 1, 1)
        self.groupBox_16 = QtWidgets.QGroupBox(self.tab_15)
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox_16)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.tblTaskListDone = QtWidgets.QTableWidget(self.groupBox_16)
        self.tblTaskListDone.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblTaskListDone.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblTaskListDone.setObjectName(_fromUtf8("tblTaskListDone"))
        self.tblTaskListDone.setColumnCount(3)
        self.tblTaskListDone.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblTaskListDone.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTaskListDone.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTaskListDone.setHorizontalHeaderItem(2, item)
        self.gridLayout_19.addWidget(self.tblTaskListDone, 0, 0, 1, 1)
        self.gridLayout_34.addWidget(self.groupBox_16, 0, 2, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem8)
        self.btnStopWorkers = QtWidgets.QPushButton(self.tab_15)
        self.btnStopWorkers.setObjectName(_fromUtf8("btnStopWorkers"))
        self.horizontalLayout_14.addWidget(self.btnStopWorkers)
        self.btnUpdateTaskList = QtWidgets.QPushButton(self.tab_15)
        self.btnUpdateTaskList.setObjectName(_fromUtf8("btnUpdateTaskList"))
        self.horizontalLayout_14.addWidget(self.btnUpdateTaskList)
        self.cbxUpdateTaskList = QtWidgets.QCheckBox(self.tab_15)
        self.cbxUpdateTaskList.setObjectName(_fromUtf8("cbxUpdateTaskList"))
        self.horizontalLayout_14.addWidget(self.cbxUpdateTaskList)
        self.gridLayout_34.addLayout(self.horizontalLayout_14, 1, 0, 1, 3)
        self.tabWidget.addTab(self.tab_15, _fromUtf8(""))
        self.tab_20 = QtWidgets.QWidget()
        self.tab_20.setObjectName(_fromUtf8("tab_20"))
        self.gridLayout_42 = QtWidgets.QGridLayout(self.tab_20)
        self.gridLayout_42.setObjectName(_fromUtf8("gridLayout_42"))
        self.frame_3 = QtWidgets.QFrame(self.tab_20)
        self.frame_3.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_14.setContentsMargins(0,0,0,0)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.cbxTaskLogsFilterVisible = QtWidgets.QCheckBox(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cbxTaskLogsFilterVisible.setFont(font)
        self.cbxTaskLogsFilterVisible.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cbxTaskLogsFilterVisible.setChecked(True)
        self.cbxTaskLogsFilterVisible.setObjectName(_fromUtf8("cbxTaskLogsFilterVisible"))
        self.horizontalLayout_17.addWidget(self.cbxTaskLogsFilterVisible)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem9)
        self.verticalLayout_14.addLayout(self.horizontalLayout_17)
        self.frameLogFilter = QtWidgets.QFrame(self.frame_3)
        self.frameLogFilter.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frameLogFilter.setFrameShape(QtWidgets.QFrame.Box)
        self.frameLogFilter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLogFilter.setObjectName(_fromUtf8("frameLogFilter"))
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frameLogFilter)
        self.verticalLayout_6.setContentsMargins(17, -1, -1, -1)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label = QtWidgets.QLabel(self.frameLogFilter)
        self.label.setMinimumSize(QtCore.QSize(85, 0))
        self.label.setMaximumSize(QtCore.QSize(85, 16777215))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_25.addWidget(self.label)
        self.cmbLogsCategory = QtWidgets.QComboBox(self.frameLogFilter)
        self.cmbLogsCategory.setObjectName(_fromUtf8("cmbLogsCategory"))
        self.horizontalLayout_25.addWidget(self.cmbLogsCategory)
        self.verticalLayout_6.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_3 = QtWidgets.QLabel(self.frameLogFilter)
        self.label_3.setMinimumSize(QtCore.QSize(85, 0))
        self.label_3.setMaximumSize(QtCore.QSize(85, 16777215))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_27.addWidget(self.label_3)
        self.cmbLogsTask = QtWidgets.QComboBox(self.frameLogFilter)
        self.cmbLogsTask.setObjectName(_fromUtf8("cmbLogsTask"))
        self.horizontalLayout_27.addWidget(self.cmbLogsTask)
        self.verticalLayout_6.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_5 = QtWidgets.QLabel(self.frameLogFilter)
        self.label_5.setMinimumSize(QtCore.QSize(85, 0))
        self.label_5.setMaximumSize(QtCore.QSize(85, 16777215))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_28.addWidget(self.label_5)
        self.txtLogContains = QtWidgets.QLineEdit(self.frameLogFilter)
        self.txtLogContains.setObjectName(_fromUtf8("txtLogContains"))
        self.horizontalLayout_28.addWidget(self.txtLogContains)
        self.verticalLayout_6.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem10)
        self.btnSearchLogs = QtWidgets.QPushButton(self.frameLogFilter)
        self.btnSearchLogs.setObjectName(_fromUtf8("btnSearchLogs"))
        self.horizontalLayout_29.addWidget(self.btnSearchLogs)
        self.verticalLayout_6.addLayout(self.horizontalLayout_29)
        self.verticalLayout_14.addWidget(self.frameLogFilter)
        self.groupBox_11 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_11.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_11.setMaximumSize(QtCore.QSize(450, 16777215))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.gridLayout_31 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_31.setObjectName(_fromUtf8("gridLayout_31"))
        self.tblTaskLogs = QtWidgets.QTableWidget(self.groupBox_11)
        self.tblTaskLogs.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblTaskLogs.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblTaskLogs.setObjectName(_fromUtf8("tblTaskLogs"))
        self.tblTaskLogs.setColumnCount(3)
        self.tblTaskLogs.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblTaskLogs.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTaskLogs.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTaskLogs.setHorizontalHeaderItem(2, item)
        self.gridLayout_31.addWidget(self.tblTaskLogs, 0, 0, 1, 1)
        self.verticalLayout_14.addWidget(self.groupBox_11)
        self.gridLayout_42.addWidget(self.frame_3, 0, 0, 1, 1)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_20)
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.gridLayout_32 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_32.setObjectName(_fromUtf8("gridLayout_32"))
        self.txtTaskLog = QtWidgets.QTextEdit(self.groupBox_12)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setItalic(False)
        self.txtTaskLog.setFont(font)
        self.txtTaskLog.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.txtTaskLog.setObjectName(_fromUtf8("txtTaskLog"))
        self.gridLayout_32.addWidget(self.txtTaskLog, 0, 0, 1, 1)
        self.verticalLayout_15.addWidget(self.groupBox_12)
        self.gridLayout_42.addLayout(self.verticalLayout_15, 0, 1, 1, 1)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem11)
        self.btnRerunTask = QtWidgets.QPushButton(self.tab_20)
        self.btnRerunTask.setObjectName(_fromUtf8("btnRerunTask"))
        self.horizontalLayout_22.addWidget(self.btnRerunTask)
        self.gridLayout_42.addLayout(self.horizontalLayout_22, 1, 0, 1, 2)
        self.tabWidget.addTab(self.tab_20, _fromUtf8(""))
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName(_fromUtf8("tab_16"))
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.tab_16)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_16 = QtWidgets.QLabel(self.tab_16)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_7.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.tab_16)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_7.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.tab_16)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_7.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.tab_16)
        self.label_19.setText(_fromUtf8(""))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_7.addWidget(self.label_19)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.lblEmailIcon2 = QtWidgets.QLabel(self.tab_16)
        self.lblEmailIcon2.setMinimumSize(QtCore.QSize(0, 0))
        self.lblEmailIcon2.setObjectName(_fromUtf8("lblEmailIcon2"))
        self.horizontalLayout_19.addWidget(self.lblEmailIcon2)
        self.label_21 = QtWidgets.QLabel(self.tab_16)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_19.addWidget(self.label_21)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem12)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.lblSkypeLogo = QtWidgets.QLabel(self.tab_16)
        self.lblSkypeLogo.setObjectName(_fromUtf8("lblSkypeLogo"))
        self.horizontalLayout_20.addWidget(self.lblSkypeLogo)
        self.label_22 = QtWidgets.QLabel(self.tab_16)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_20.addWidget(self.label_22)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem13)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.lblEmailIcon = QtWidgets.QLabel(self.tab_16)
        self.lblEmailIcon.setMinimumSize(QtCore.QSize(0, 0))
        self.lblEmailIcon.setObjectName(_fromUtf8("lblEmailIcon"))
        self.horizontalLayout_18.addWidget(self.lblEmailIcon)
        self.label_20 = QtWidgets.QLabel(self.tab_16)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_18.addWidget(self.label_20)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem14)
        self.verticalLayout_7.addLayout(self.horizontalLayout_18)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem15)
        self.horizontalLayout_21.addLayout(self.verticalLayout_7)
        spacerItem16 = QtWidgets.QSpacerItem(406, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem16)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.frame_2 = QtWidgets.QFrame(self.tab_16)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_26 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_26.setObjectName(_fromUtf8("gridLayout_26"))
        self.lblSensePostLogo = QtWidgets.QLabel(self.frame_2)
        self.lblSensePostLogo.setMinimumSize(QtCore.QSize(300, 250))
        self.lblSensePostLogo.setObjectName(_fromUtf8("lblSensePostLogo"))
        self.gridLayout_26.addWidget(self.lblSensePostLogo, 0, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.frame_2)
        self.label_23 = QtWidgets.QLabel(self.tab_16)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_12.addWidget(self.label_23)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem17)
        self.horizontalLayout_21.addLayout(self.verticalLayout_12)
        self.tabWidget.addTab(self.tab_16, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_6.setCurrentIndex(0)
        self.tabWidget_5.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.lblSummaryLabel.setText(_translate("MainWindow", "Identified 0 hosts, 0 open ports, 0 shells", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Open Ports", None))
        item = self.tblOpenPortsSummary.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Port", None))
        item = self.tblOpenPortsSummary.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Count", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Domains", None))
        item = self.tblDomains.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Domain Name", None))
        item = self.tblDomains.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Domain Admins", None))
        item = self.tblDomains.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Known Passwords", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Vulns", None))
        item = self.tblVulnsSummary.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Vuln", None))
        item = self.tblVulnsSummary.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Count", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Credentials", None))
        item = self.tblCredsSummary.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Type", None))
        item = self.tblCredsSummary.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Count", None))
        self.btnUpdateSummary.setText(_translate("MainWindow", "Update Summary", None))
        self.cbxUpdateSummary.setText(_translate("MainWindow", "Continuously", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Summary", None))
        self.cbxHostsFilterVisible.setText(_translate("MainWindow", "Filter", None))
        self.cmbHostFilterField.setItemText(1, _translate("MainWindow", "IP Address", None))
        self.cmbHostFilterField.setItemText(2, _translate("MainWindow", "Host Name", None))
        self.cmbHostFilterField.setItemText(3, _translate("MainWindow", "Port", None))
        self.cmbHostFilterField.setItemText(4, _translate("MainWindow", "Domain", None))
        self.btnSearchHosts.setText(_translate("MainWindow", "Search", None))
        self.label_2.setText(_translate("MainWindow", "Name", None))
        self.label_4.setText(_translate("MainWindow", "OS", None))
        self.label_6.setText(_translate("MainWindow", "Architecture", None))
        self.label_8.setText(_translate("MainWindow", "Language", None))
        self.label_10.setText(_translate("MainWindow", "Domain", None))
        self.groupBox_13.setTitle(_translate("MainWindow", "Open Ports", None))
        item = self.tblHostPorts.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Port", None))
        self.groupBox_14.setTitle(_translate("MainWindow", "Vulns", None))
        item = self.tblHostVulns.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Port", None))
        item = self.tblHostVulns.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Vuln", None))
        self.groupBox_15.setTitle(_translate("MainWindow", "Creds Summary", None))
        item = self.tblHostCredsSummary.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Type", None))
        item = self.tblHostCredsSummary.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Count", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Host Info", None))
        item = self.tblLocalCreds.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Username", None))
        item = self.tblLocalCreds.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Password", None))
        item = self.tblLocalCreds.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "LM Hash", None))
        item = self.tblLocalCreds.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "NTLM Hash", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_4), _translate("MainWindow", "Local Creds", None))
        item = self.tblDomainCreds.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Domain", None))
        item = self.tblDomainCreds.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Username", None))
        item = self.tblDomainCreds.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Password", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_5), _translate("MainWindow", "Domain Creds", None))
        item = self.tblAvailableTokens.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Token", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_17), _translate("MainWindow", "Tokens", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Creds", None))
        item = self.tblExploitLogs.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Vector", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "Msf Logs", None))
        self.btnOpenRDPSession.setText(_translate("MainWindow", "Open RDP Session", None))
        self.btnAddHost.setText(_translate("MainWindow", "Add Host", None))
        self.btnUpdateHosts.setText(_translate("MainWindow", "Update Hosts", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Hosts", None))
        self.label_7.setText(_translate("MainWindow", "Vulnerability", None))
        item = self.tblVulnerableHosts.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "IP Address", None))
        item = self.tblVulnerableHosts.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Host Name", None))
        item = self.tblVulnerableHosts.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Port", None))
        item = self.tblVulnerableHosts.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Vulnerability", None))
        item = self.tblVulnerableHosts.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Vuln Notes", None))
        self.btnRefreshVulnerabilitiesTab.setText(_translate("MainWindow", "Refresh", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_25), _translate("MainWindow", "Vulnerabilities", None))
        item = self.tblDomains_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Domain", None))
        item = self.tblDomainControllers.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "IP Address", None))
        item = self.tblDomainControllers.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Host Name", None))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_22), _translate("MainWindow", "Domain Controllers", None))
        item = self.tblDomainControllerCredMap.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "IP Address", None))
        item = self.tblDomainControllerCredMap.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Host Name", None))
        item = self.tblDomainControllerCredMap.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Domain", None))
        item = self.tblDomainControllerCredMap.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Username", None))
        item = self.tblDomainControllerCredMap.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Password", None))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_24), _translate("MainWindow", "Cred Map", None))
        self.groupBox_21.setTitle(_translate("MainWindow", "Groups", None))
        item = self.tblDomainGroups.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Groups", None))
        self.groupBox_22.setTitle(_translate("MainWindow", "Users", None))
        item = self.tblDomainGroupUsers.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Users", None))
        self.groupBox_23.setTitle(_translate("MainWindow", "Sub Groups", None))
        item = self.tblDomainSubGroups.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Groups", None))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_23), _translate("MainWindow", "Users and Groups", None))
        self.btnUpdateDomains.setText(_translate("MainWindow", "Update", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_21), _translate("MainWindow", "Domains", None))
        self.groupBox.setTitle(_translate("MainWindow", "Hosts", None))
        self.tblWebsites.setSortingEnabled(True)
        item = self.tblWebsites.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Host", None))
        item = self.tblWebsites.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Host Name", None))
        item = self.tblWebsites.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Port", None))
        item = self.tblWebsites.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Title", None))
        item = self.tblWebsites.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "ID", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "Website", None))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_14), _translate("MainWindow", "Screenshot", None))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_19), _translate("MainWindow", "HTML", None))
        self.btnUpdateWebsites.setText(_translate("MainWindow", "Update", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "Websites", None))
        item = self.tblAllDomainCreds.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Domain", None))
        item = self.tblAllDomainCreds.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Username", None))
        item = self.tblAllDomainCreds.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Password", None))
        item = self.tblAllDomainCreds.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "LM Hash", None))
        item = self.tblAllDomainCreds.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "NTLM Hash", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_10), _translate("MainWindow", "Domain Creds", None))
        self.groupBox_18.setTitle(_translate("MainWindow", "Valid Creds", None))
        item = self.tblValidDomainCreds.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Host", None))
        item = self.tblValidDomainCreds.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Domain", None))
        item = self.tblValidDomainCreds.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Username", None))
        item = self.tblValidDomainCreds.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Password", None))
        self.groupBox_19.setTitle(_translate("MainWindow", "Invalid Creds", None))
        item = self.tblInvalidDomainCreds.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Host", None))
        item = self.tblInvalidDomainCreds.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Domain", None))
        item = self.tblInvalidDomainCreds.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Username", None))
        item = self.tblInvalidDomainCreds.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Password", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_13), _translate("MainWindow", "Domain Creds Pivot Map", None))
        item = self.tblAllLocalCreds.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Username", None))
        item = self.tblAllLocalCreds.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Password", None))
        item = self.tblAllLocalCreds.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "LM Hash", None))
        item = self.tblAllLocalCreds.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "NTLM Hash", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_11), _translate("MainWindow", "Local Creds", None))
        item = self.tblTokens.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Tokens", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_18), _translate("MainWindow", "Tokens", None))
        self.btnAddDomainCreds.setText(_translate("MainWindow", "Add Domain Creds", None))
        self.btnImportLoot.setText(_translate("MainWindow", "Import from msf loot", None))
        self.btnSyncJohnPotFile.setText(_translate("MainWindow", "Get creds from pot file", None))
        self.btnUpdateCreds.setText(_translate("MainWindow", "Update", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "Credentials", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Pending", None))
        item = self.tblTaskListPending.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Category", None))
        item = self.tblTaskListPending.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Task", None))
        item = self.tblTaskListPending.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Count", None))
        self.groupBox_20.setTitle(_translate("MainWindow", "Eventless Tasks", None))
        item = self.tblTaskListPending_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Category", None))
        item = self.tblTaskListPending_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Task", None))
        item = self.tblTaskListPending_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Count", None))
        self.groupBox_17.setTitle(_translate("MainWindow", "In Progress", None))
        item = self.tblTaskListInProgress.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Category", None))
        item = self.tblTaskListInProgress.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Task", None))
        item = self.tblTaskListInProgress.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Count", None))
        self.groupBox_16.setTitle(_translate("MainWindow", "Completed", None))
        item = self.tblTaskListDone.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Category", None))
        item = self.tblTaskListDone.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Task", None))
        item = self.tblTaskListDone.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Count", None))
        self.btnStopWorkers.setToolTip(_translate("MainWindow", "Stop new tasks from running after the current ones finish", None))
        self.btnStopWorkers.setText(_translate("MainWindow", "Stop Threads", None))
        self.btnUpdateTaskList.setText(_translate("MainWindow", "Update", None))
        self.cbxUpdateTaskList.setText(_translate("MainWindow", "Continuously", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_15), _translate("MainWindow", "Task List", None))
        self.cbxTaskLogsFilterVisible.setText(_translate("MainWindow", "Filter", None))
        self.label.setText(_translate("MainWindow", "Category", None))
        self.label_3.setText(_translate("MainWindow", "Task", None))
        self.label_5.setText(_translate("MainWindow", "Log contains", None))
        self.btnSearchLogs.setText(_translate("MainWindow", "Search", None))
        self.groupBox_11.setTitle(_translate("MainWindow", " Tasks", None))
        item = self.tblTaskLogs.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Category", None))
        item = self.tblTaskLogs.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Task", None))
        item = self.tblTaskLogs.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "ID", None))
        self.groupBox_12.setTitle(_translate("MainWindow", "Log", None))
        self.btnRerunTask.setText(_translate("MainWindow", "Re-run task", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_20), _translate("MainWindow", "Logs", None))
        self.label_16.setText(_translate("MainWindow", "autodane v2.0", None))
        self.label_17.setText(_translate("MainWindow", "Written by Dane Goodwin,", None))
        self.label_18.setText(_translate("MainWindow", "Security Analyst at SensePost", None))
        self.lblEmailIcon2.setText(_translate("MainWindow", "emailicon", None))
        self.label_21.setText(_translate("MainWindow", "Dane@SensePost.com", None))
        self.lblSkypeLogo.setText(_translate("MainWindow", "skypelogo", None))
        self.label_22.setText(_translate("MainWindow", "dane_goodwin", None))
        self.lblEmailIcon.setText(_translate("MainWindow", "emailicon", None))
        self.label_20.setText(_translate("MainWindow", "Research@SensePost.com", None))
        self.lblSensePostLogo.setText(_translate("MainWindow", "SP Logo", None))
        self.label_23.setText(_translate("MainWindow", "SensePost.com", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_16), _translate("MainWindow", "About", None))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
